// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC2H8lfAXKEE3nEonLKFEobIy3FV723WwY',
    appId: '1:993669966420:web:8ffb2c146d511329835bc1',
    messagingSenderId: '993669966420',
    projectId: 'boutique-shop-44f26',
    authDomain: 'boutique-shop-44f26.firebaseapp.com',
    storageBucket: 'boutique-shop-44f26.appspot.com',
    measurementId: 'G-G2QKM9SWN4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAeMCj2yK6OJoTwB_gjfxA_Ra0VjFBOL9M',
    appId: '1:993669966420:android:4849bdd9e5ed3b7a835bc1',
    messagingSenderId: '993669966420',
    projectId: 'boutique-shop-44f26',
    storageBucket: 'boutique-shop-44f26.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA_F3HNq6LqM9UKJTr3z2tm3Ua51fVLKkk',
    appId: '1:993669966420:ios:5284d64862dea959835bc1',
    messagingSenderId: '993669966420',
    projectId: 'boutique-shop-44f26',
    storageBucket: 'boutique-shop-44f26.appspot.com',
    iosBundleId: 'com.example.boutiqueShop',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA_F3HNq6LqM9UKJTr3z2tm3Ua51fVLKkk',
    appId: '1:993669966420:ios:059f11360fbbdec4835bc1',
    messagingSenderId: '993669966420',
    projectId: 'boutique-shop-44f26',
    storageBucket: 'boutique-shop-44f26.appspot.com',
    iosBundleId: 'com.example.boutiqueShop.RunnerTests',
  );
}
